### ISSUE TITLE
Custom build fails with error components.split(',')

### ISSUE THREAD

**Issue by anandanand84** [contactlab/contactlab-ui-components#104]
Just followed the read me but could not use single command, below is the stack trace

```
yarn run build:single tooltip,radio,checkbox no-polymer
yarn run v0.18.1
$ node -e 'require("./webpack").singleWebpack()'
/Users/AAravindan/dev/traderslab/projects/contactlab-ui-components/webpack.js:53
  components = components.split(',')
                         ^

TypeError: Cannot read property 'split' of undefined
    at Object.module.exports.singleWebpack (/Users/AAravindan/dev/traderslab/projects/contactlab-ui-components/webpack.js:53:26)
    at [eval]:1:22
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
    at bootstrap_node.js:315:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error Command failed with exit code 1.
```

**Comment by LasaleFamine** [comment]
Hello @anandanand84, 
thank you for your reporting.

I'm investigating about the issue and I'm able to reproduce it. 
The problem seems related to the args that are not sent to the `prebuild` NPM script. 

I will be back ASAP with a fix for this.
